### ISSUE TITLE
can't open file 'manage.py': [Errno 2] No such file or directory when using volumes

### ISSUE THREAD

**Issue by euri10** [testdrivenio/testdriven-app-2.2#15]
just bought the course and so far so good, except one thing I'm stuck at at the very beginning setting up docker.
the course says page 21

> 
> The volume is used to mount the code into the container. This is a must for a development
> environment in order to update the container whenever a change to the source code is made.
> Without this, you would have to re-build the image after each code change.

if I use the docker-compose-dev.yml with the volumes commented 
```
version: '3.4'
services:
  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
#    volumes:
#      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
```
I can reach the app at  http://DOCKER_MACHINE_IP:5001/users/ping after I run `docker-compose -f docker-compose-dev.yml up -d`

But as soon as I uncomment it, I got this weird error trying to up the config (I removed the -d flag to get the error):

```
docker-compose -f docker-compose-dev.yml up          
Starting users ... done
Attaching to users
users    | python: can't open file 'manage.py': [Errno 2] No such file or directory
users exited with code 2
```

I'm positive I'm running docker-compose on the correct machine:
```
docker-machine active
testdriven-dev
```
I'm using those versions:

```
docker -v && docker-compose -v && docker-machine -v
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.2, build a133471
docker-machine version 0.14.0, build 89b8332
```

and so far my tree looks like that:

```
(project-tOIAx_A8) ➜  testdriven-app tree
.
├── docker-compose-dev.yml
└── services
    └── users
        ├── Dockerfile-dev
        ├── manage.py
        ├── Pipfile
        ├── Pipfile.lock
        ├── project
        │   ├── config.py
        │   ├── __init__.py
        │   └── __pycache__
        │       ├── config.cpython-36.pyc
        │       └── __init__.cpython-36.pyc
        └── requirements.txt

4 directories, 10 files
```
Any idea where I could look at ?
